[package]
name = "not_working"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
serde_json = "1.0.79"
valuable = "0.1.0"
valuable-derive = "0.1.0"
valuable-serde = "0.1.0"
